export const ADD_USER_REGISTER = "ADD_USER_REGISTER";
export const ADD_USER_SIGNIN = "ADD_USER_SIGNIN";
export const ADD_USER_GOOGLE = "ADD_USER_GOOGLE";
export const GET_USER = "GET_USER";

// FORMATION

export const ADD_FORMATION = "ADD_FORMATION";
export const GET_FORMATION = "GET_FORMATION";
